spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 2020
    url: jdbc:postgresql://localhost:5432/peakSpace
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



#When you will click 'create' you shout click to 'always'! from Myrzaiym


    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:dataInit/dataInit.sql
      mode: never
app:
  jwt:
    secret: Myrzaiym
      #  #DATA-INIT
      #  spring.jpa.defer-datasource-initialization=true
      #  spring.sql.init.data-locations=classpath:datainit/dataInit.sql
      #  spring.sql.init.mode=never
      #
      #