spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: mirlan001m.
        url: jdbc:postgresql://localhost:5432/peakspace
        username: postgres
    mail:
        host: smtp.gmail.com
        port: 587
        username: arstanbeekovvv@gmail.com
        password: gnfh xali juew hdna
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
            defer-datasource-initialization: true
    sql:
        init:
            data-locations: classpath:dataInit/dataInit.sql
            mode: never
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
server:
    error:
        include-stacktrace: always
app:
    jwt:
        secret: peak-space-java12

cloud:
    aws:
        region: eu-north-1
        accessKey: AKIAZI2LDVKOR6V4MDP7
        secretKey: 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
    s3:
        bucketName: peakspacebucket
