spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: 2020
        url: jdbc:postgresql://localhost:5432/peakSpace
        username: postgres
    mail:
        host: smtp.gmail.com
        port: 587
        username: arstanbeekovvv@gmail.com
        password: gnfh xali juew hdna
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
            defer-datasource-initialization: true
    sql:
        init:
            data-locations: classpath:dataInit/dataInit.sql
            mode: never
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
server:
    error:
        include-stacktrace: always
app:
    jwt:
        secret: peak-space-java12

#When you will click 'create' you shout click to 'always'! from Myrzaiym

      #  #DATA-INIT
#        spring.jpa.defer-datasource-initialization=true
#        spring.sql.init.data-locations=classpath:datainit/dataInit.sql
#        spring.sql.init.mode=never
