spring:
    datasource:
        driver-class-name:
        password:
        url:
        username:
    mail:
        host: smtp.gmail.com
        port: 587
        username: arstanbeekovvv@gmail.com
        password: gnfh xali juew hdna
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
jpa:
    hibernate:
        ddl-auto:
        show-sql: true

server:
    error:
        include-stacktrace: always

app:
    jwt:
        secret: peak-space-java12