spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: mirlan001m.
    url: jdbc:postgresql://localhost:5432/peakspace
    username: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: arstanbeekovvv@gmail.com
    password: gnfh xali juew hdna
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      #When you will click 'create' you shout click to 'always'! from Myrzaiym
      defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:dataInit/dataInit.sql
      mode: always

    #  #DATA-INIT
    #  spring.jpa.defer-datasource-initialization=true
    #  spring.sql.init.data-locations=classpath:datainit/dataInit.sql
    #  spring.sql.init.mode=never
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  error:
    include-stacktrace: always
app:
  jwt:
    secret: Java12
nikita:
  api:
    url: https://api.nikita.kg/sms/
    key: bfc87413578d8bf8181838ca5418239b
