spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: yiman
        url: jdbc:postgresql://localhost:5434/peakspace
        username: postgres
    mail:
        host: smtp.gmail.com
        port: 587
        username: arstanbeekovvv@gmail.com
        password: gnfh xali juew hdna
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
            defer-datasource-initialization: true
    sql:
        init:
            data-locations: classpath:dataInit/dataInit.sql
            mode: never
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
server:
    error:
        include-stacktrace: never
    port: 8090
app:
    jwt:
        secret: peak-space-java12

cloud:
    aws:
        region: eu-north-1
        accessKey: AKIAZI2LDVKOR6V4MDP7
        secretKey: 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
    s3:
        bucketName: peakspacebucket

#When you will click 'create' you shout click to 'always'! from Myrzaiym

      #  #DATA-INIT
#        spring.jpa.defer-datasource-initialization=true
#        spring.sql.init.data-locations=classpath:datainit/dataInit.sql
#        spring.sql.init.mode=never