spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 1234
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: arstanbeekovvv@gmail.com
    password: gnfh xali juew hdna
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:dataInit/dataInit.sql
      mode: never
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
server:
  error:
    include-stacktrace: always
app:
  jwt:
    secret: peak-space-java12

cloud:
  aws:
    region: eu-north-1
    accessKey: AKIAZI2LDVKOR6V4MDP7
    secretKey: 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
  s3:
    bucketName: peakspacebucket